-- Seed data for testing
-- This file contains sample listings for development

INSERT INTO public.listings (
  title,
  price,
  location,
  city,
  bedrooms,
  property_type,
  has_photos,
  fb_post_url,
  fb_group_name,
  post_date,
  description,
  images,
  is_verified
) VALUES
  (
    '2BR Condo in BGC near High Street',
    35000,
    'BGC, Taguig',
    'Taguig',
    '2',
    'condo',
    true,
    'https://facebook.com/groups/BGCrentals/posts/123456',
    'BGC Rentals and Apartments',
    NOW() - INTERVAL '2 days',
    'Fully furnished 2 bedroom condo with parking. Walking distance to High Street and Market Market. With amenities.',
    ARRAY['https://example.com/image1.jpg', 'https://example.com/image2.jpg'],
    true
  ),
  (
    'Studio Unit for Rent in Makati',
    18000,
    'Salcedo Village, Makati',
    'Makati',
    'studio',
    'apartment',
    true,
    'https://facebook.com/groups/makatiapartments/posts/234567',
    'Makati Apartments for Rent',
    NOW() - INTERVAL '5 days',
    'Cozy studio unit, semi-furnished. Near Ayala Avenue and MRT.',
    ARRAY['https://example.com/image3.jpg'],
    true
  ),
  (
    '3BR House in Quezon City',
    25000,
    'Teacher''s Village, QC',
    'Quezon City',
    '3',
    'house',
    true,
    'https://facebook.com/groups/QCrentals/posts/345678',
    'QC House and Lot for Rent',
    NOW() - INTERVAL '1 day',
    'Spacious house with garage for 2 cars. Near UP Diliman.',
    ARRAY['https://example.com/image4.jpg', 'https://example.com/image5.jpg'],
    true
  ),
  (
    'Room for Rent in Ortigas',
    8000,
    'Ortigas Center, Pasig',
    'Pasig',
    '1',
    'room',
    false,
    'https://facebook.com/groups/ortigasrentals/posts/456789',
    'Ortigas Rentals',
    NOW() - INTERVAL '3 days',
    'Solo room in shared apartment. All utilities included.',
    ARRAY[]::TEXT[],
    true
  ),
  (
    '1BR Apartment near Greenbelt',
    28000,
    'Legazpi Village, Makati',
    'Makati',
    '1',
    'apartment',
    true,
    'https://facebook.com/groups/makatiapartments/posts/567890',
    'Makati Apartments for Rent',
    NOW() - INTERVAL '4 days',
    'Modern 1BR apartment, newly renovated. 5 mins walk to Greenbelt.',
    ARRAY['https://example.com/image6.jpg'],
    true
  ),
  (
    'Studio Condo in Eastwood',
    15000,
    'Eastwood City, QC',
    'Quezon City',
    'studio',
    'condo',
    true,
    'https://facebook.com/groups/eastwoodrentals/posts/678901',
    'Eastwood City Rentals',
    NOW() - INTERVAL '6 days',
    'Affordable studio unit with balcony. Near IT offices.',
    ARRAY['https://example.com/image7.jpg', 'https://example.com/image8.jpg'],
    true
  ),
  (
    '2BR House in Paranaque',
    20000,
    'BF Homes, Paranaque',
    'Paranaque',
    '2',
    'house',
    true,
    'https://facebook.com/groups/paranaquerentals/posts/789012',
    'Paranaque House for Rent',
    NOW() - INTERVAL '2 days',
    'Bungalow house in quiet subdivision. Pet-friendly.',
    ARRAY['https://example.com/image9.jpg'],
    true
  ),
  (
    'Furnished 1BR in Alabang',
    22000,
    'Filinvest City, Alabang',
    'Muntinlupa',
    '1',
    'condo',
    true,
    'https://facebook.com/groups/alabangrentals/posts/890123',
    'Alabang Rentals',
    NOW() - INTERVAL '1 day',
    'Fully furnished 1BR condo with fiber internet. Near Festival Mall.',
    ARRAY['https://example.com/image10.jpg', 'https://example.com/image11.jpg'],
    true
  );